# Generated by Django 6.0.1 on 2026-04-02 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_project_project_notes_project_project_progress_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_progress',
            field=models.CharField(choices=[('pending', 'Pending'), ('ongoing', 'Ongoing'), ('completed', 'Completed'), ('not interested', 'Not Interested')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('ongoing', 'Ongoing'), ('completed', 'Completed'), ('not interested', 'Not Interested')], default='pending', max_length=20),
        ),
    ]
